### ISSUE TITLE
Trello integration [10]

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro#82]
As a user
I want to be able to track time on a Trello card
So that I can have a summary of how much time the card took to complete.

- [Trello API](https://trello.com/docs/)

- [x] Authorization on behalf of the user
- [x] $resource's for relevant endpoints
- [ ] Trello card picker
  - [ ] modal
  - [ ] list of cards to choose from
- [ ] associate a card (by id, shortlink..) to a pomodoro

**Comment by nicoespeon** [comment]
This would be awesome :+1:

I'm starting using pomodoro.cc. I'll give you feedbacks if it could help :smiley:

**Comment by christian-fei** [comment]
Awesome, yesss feedback would be very useful, especially with features you find could fit your workflow!
