### ISSUE TITLE
Improve guidance on pomodoro technique

### ISSUE THREAD

**Issue by nicoespeon** [christian-fei/pomodoro#92]
As a user
I want to know which break should I take after a pomodoro
So that I can follow pomodoro technique recommandations

As an example, for now I could find me wondering questions such as:

- is it my third or fourth pomodoro?
- should I now take a 5-min or 15-min break?
- let's check the stats… oh yeah I already take the 15-min break 2 pomodoro ago, there is one more then it's 15-min break again… if I correctly remember…

**Comment by christian-fei** [comment]
hmm interesting!
Thank you, will look into it
