### ISSUE TITLE
[8] Shared pomodoro (8)

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro#95]
- [x] save to private pomodori
- [x] synchronize time between clients

**Comment by liuggio** [comment]
:+1: is this feature already available?

**Comment by christian-fei** [comment]
Hello Giulio,
no excuses this time, I will see what I can get done this weekend :)

**Comment by christian-fei** [comment]
Hello Giulio,
got a beta out :)

https://pomodoro.cc/public/123

For now just replace the pomodoro id with some random you like.

More coming soon :)

Thanks again

**Comment by liuggio** [comment]
Woow this is a great job

**Comment by christian-fei** [comment]
Thank you
